baseURL = "/"
defaultContentLanguage = "en"
title = "MDFriday Hero"
author = "MDFriday (mdfriday.com)"
description = "Say hi to MDFriday"
googleAnalytics = "GA-000000000-0"

[module]
    [[module.imports]]
        path = "github.com/mdfriday/theme-hero"

[languages]
[languages.en]
languageName = 'English'
contentDir = 'content.en'
weight = 1

[languages.zh]
languageName = '中文'
contentDir = 'content.zh'
weight = 2